#!/bin/bash
# chmod ug+x wp
clear

echo 'WordPressifying...'
echo 'Compiling & compressing WordPress Plugins ...'

cd ./wp-content/plugins/react/toolkit-admin && yarn build
cd ../pingpong  && yarn && yarn build

echo 'BASTA'
