#!/bin/bash
# chmod ug+x wp
clear

cd ./wp-content/plugins/
mkdir temp

echo 'WordPressifying listingslab-toolkit ...'
cd ./listingslab-toolkit/react && yarn build && cd ../../
mv ./listingslab-toolkit/react/ ./temp
mkdir ./listingslab-toolkit/react && mkdir ./listingslab-toolkit/react/build
mv ./temp/react/build ./listingslab-toolkit/react
zip -r listingslab-toolkit.zip listingslab-toolkit
rm -rf ./listingslab-toolkit/react
mkdir ./listingslab-toolkit/react
mv ./temp/react ./listingslab-toolkit

echo 'WordPressifying listingslab-pingpong ...'
cd ./listingslab-pingpong/react && yarn build && cd ../../
mv ./listingslab-pingpong/react/ ./temp
mkdir ./listingslab-pingpong/react && mkdir ./listingslab-pingpong/react/build
mv ./temp/react/build ./listingslab-pingpong/react
zip -r listingslab-pingpong.zip listingslab-pingpong
rm -rf ./listingslab-pingpong/react
mkdir ./listingslab-pingpong/react
mv ./temp/react ./listingslab-pingpong

echo 'WordPressifying listingslab-kart ...'
cd ./listingslab-kart/react && yarn build && cd ../../
mv ./listingslab-kart/react/ ./temp
mkdir ./listingslab-kart/react && mkdir ./listingslab-kart/react/build
mv ./temp/react/build ./listingslab-kart/react
zip -r listingslab-kart.zip listingslab-kart
rm -rf ./listingslab-kart/react
mkdir ./listingslab-kart/react
mv ./temp/react ./listingslab-kart

echo 'WordPressifying listingslab-pwaify ...'
zip -r listingslab-pwaify.zip listingslab-pwaify

rm -rf ./temp

echo 'WordPressifying completed'
